version: "3.8"

services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - proxy
    ports:
      - "3011:3000"
  
networks:
  proxy:
    external: true
    name: traefik_proxy