version: "3.8"

services:
  nextjs:
    container_name: nextjs-app-site-portfolio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3098:3000"
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
